### ISSUE TITLE
Elastic search results seem to be ranked...

### ISSUE THREAD

**Issue by rgabbard** [isi-vista/curated-training-annotator#16]
and we want a random sampling from all matching documents. How can this be accomplished?

**Comment by shinyichen** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html

**Comment by rgabbard** [comment]
It looks like https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-random is what we want; use a seed and use the document name as the field

**Comment by rgabbard** [comment]
This doesn't seem to be working - more details to follow

**Comment by rgabbard** [comment]
@qpwo  :

To reproduce the undesirable behavior:
* log in to Inception
* go to your "Conflict.Attack" project
* Click "search"
* search for "strike"
* Get a bunch of documents which are very dense in mentions of "strike" in the labor strike sense:

![Screen Shot 2019-05-23 at 11 54 15 AM](https://user-images.githubusercontent.com/7139661/58267410-8f35c700-7d51-11e9-8e61-065c13643d4c.png)

The desired behavior is that we should have just a random sample of document containing "strike".  We thought this was fixed in https://github.com/inception-project/inception/pull/969/files by requesting the Elastic Search using random scoring when returning results, but that doesn't seem to be happening.

The port to query our ElasticSearch server is http://gaiadev01.isi.edu:9200 . You'll need to be on the ISI VPN.  The code on the PR above will tell you what JSON we are sending.  I would suggest first trying to launch this query manually against our ElasticSearch instance using `curl` and seeing if you get the same results.  If you do, dig into the ElasticSearch docs to figure out what we are doing wrong and modify the Inception code as needed.  If we don't, ping me and we can talk more.

**Comment by qpwo** [comment]
I wanted to be more sure the results are not random.

If I search 'Qdoba', then the number of 'Qdoba' occurrences in each result (starting from the first result) goes 5, 5, 5, 2, 1, 3, 2, 1, 1, 1. Searching Chipotle, the first page has 6, 5, 5, 5, 3, 5, 4, 5, 4, 5 occurrences on the respective results, and the last page has 5, 1, 4, 1, 2, 1, 1, 4, 2, 1. 'Taco Bell' has first page 2, 5, 4, 5, 3, 3, 2, 2, 1, 3 and last page 1, 1, 1, 1, 1, 2, 1, 1, 1.

Indeed it seems it's sorting by relevancy. 🤔

**Comment by qpwo** [comment]
Problem is definitely still occurring from `gaiadev01.isi.edu:9200/gigaword/_search?...` with `curl`

**Comment by rgabbard** [comment]
@qpwo : Can you post the query you sent and at least the beginning of the results?

**Comment by qpwo** [comment]
Yes (`jq` is a json formatter)
```
~/elastic-search$ curl -X GET "gaiadev01.isi.edu:9200/gigaword/_search?" -H 'Content-Type: application/json' -d'{"from": 0, "size": 10, "query":{"match":{"doc.text":"SHOT"}}}' | jq | head -n 30

{
  "took": 10,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 575141,
    "max_score": 5.978581,
    "hits": [
      {
        "_index": "gigaword",
        "_type": "texts",
        "_id": "NYT_ENG_20081113.0217",
        "_score": 5.978581,
        "_source": {
          "doc": {
	    "text": "<DOC id=\"NYT_ENG_20081113.0217\" type=\"story\"
	    >\n<HEADLINE>\nANOTHER SHOT FOR
	    J.R.\n</HEADLINE>\n<DATELINE>\nUNDATED\n</DATELINE>\n<TEXT>\n<P>\nCan
	    you believe it's been 30 years since \"Dallas\"\nbecame a\nmust-see
	    TV series? Three decades later, the Rattlesnake Bar at\nFearing's
	    in the Ritz-Carlton, Dallas, celebrates the most-watched\nepisode
	    in TV history with \"Who Shot J.R.? ... The Shot
	    Menu.\"\n</P>\n<P>\nAmong choices:\n</P>\n<P>\n-- The Sue Ellen
	    Ewing Shot: an explosive shot of 100 proof\nSouthern\nComfort to
	    match J.R. and Sue Ellen's fiery relationship.\n</P>\n<P>\n-- The
	    Bobby Ewing Shot: Kahlua and cream for his sweet side
	    with\na\nsplash of Anejo Tequila for his mysterious
	    side.\n</P>\n<P>\n-- The Pamela Ewing Shot: Is she really as sweet
	    and wholesome as\na shot\nof Hot Apple Pie?\n</P>\n<P>\n-- The
	    Cliff Barnes Shot: Absolut Peppar for absolute enemies\nJ.R.
	    &amp;amp;\nCliff.\n</P>\n<P>\n-- The Vaughn Leland Shot: A 101
	    proof shot of Wild Turkey.\n</P>\n<P>\n-- The Kristin Shepard Shot:
	    A shot of Red Devil for the woman\nwho shot\nJ.R. in cold
	    blood.\n</P>\n<P>\nEach cocktail costs $8.\n</P>\n<P>\nFearing's is
	    acclaimed chef Dean Fearing's newest
	    restaurant;\n214-922-0200.\n</P>\n</TEXT>\n</DOC>"
          },
          "metadata": {
            "id": "NYT_ENG_20081113.0217",
            "language": "en",
            "source": "",
            "timestamp": "Mon Mar 11 10:04:00 PDT 2019",
            "uri": ""
          }
        }
~/elastic-search$ curl -X GET "gaiadev01.isi.edu:9200/gigaword/_search?" -H 'Content-Type: application/json' -d'{"from": 9000, "size": 10, "query":{"match":{"doc.text":"SHOT"}}}' | jq | head -n 30

{
  "took": 33,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 575141,
    "max_score": 5.978581,
    "hits": [
      {
        "_index": "gigaword",
        "_type": "texts",
        "_id": "XIN_ENG_20080523.0272",
        "_score": 5.1518393,
        "_source": {
          "doc": {
	    "text": "<DOC id=\"XIN_ENG_20080523.0272\" type=\"other\"
	    >\n<HEADLINE>\nResults of women's shot put in China Athletics
	    Open\n</HEADLINE>\n<DATELINE>\nBEIJING, May 23
	    (Xinhua)\n</DATELINE>\n<TEXT>\nFollowings are the final results
	    of\nthe women's shot put of Good Luck Beijing China Athletics
	    Open\nhere on Friday at the National Stadium:\n1. Valerie Vili, New
	    Zealand, 19.41 meters\n2. Gong Lijiao, China, 19.09\n3. Li Ling,
	    China, 18.85\n</TEXT>\n</DOC>"
          },
          "metadata": {
            "id": "XIN_ENG_20080523.0272",
            "language": "en",
            "source": "",
            "timestamp": "Mon Mar 11 10:10:46 PDT 2019",
            "uri": ""
          }
        }

~/elastic-search$ 
```

(Line count exceeds 30 because I reflowed the `"text"` field.)

Starting at the first results, 'shot' comes up 134 times across 3262 words. Start at the 9000th result, 'shot' comes up 79 times across 6180 words.

**Comment by rgabbard** [comment]
@qpwo : If you search for `strike`, do you get the same results as you see in the GUI?

**Comment by rgabbard** [comment]
@qpwo : Also, can you try searching using the random ordering?

**Comment by qpwo** [comment]
I'm not getting the same results on GUI, but as you pointed out, I'm not using random ordering. I think I'm also not even limiting my manual query to the Conflict.Attack dataset, which should also be done. Will do these and get back to you

**Comment by rgabbard** [comment]
(As noted on Slack, but for the reference of any future readers: the same corpus is used when annotating all event types for a given language, so there is no `Conflict.Attack`-specific dataset)

**Comment by qpwo** [comment]
I believe the problem is that we are not using [`function_score`](https://www.elastic.co/guide/en/elasticsearch/reference/6.4/query-dsl-function-score-query.html) correctly.

Currently the GUI generates JSON like this:
```
{
  "size": 1000,
  "query": {
    "function_score": {
      "query": {
        "query_string": {
          "default_field": "doc.text",
          "query": "STRIKE"
        }
      },
      "random_score": {
        "seed": 5,
        "field": "_id"
      }
    }
  },
  "highlight": {
    "fields": {
      "doc.text": {}
    }
  }
}
```

After analyzing the difference in scores with and without the `random_score` portion of the JSON, I believe maybe somehow the `random_score` is being **added** to the `query` portion. I believe we need to switch from the current JSON object style to one where we first **filter** by query, and then random score within these results.

The second example on the above link is close to what I'm describing, I'll try doing it on our server in a minute.

**Comment by qpwo** [comment]
Update: Hand-writing Elasticsearch query bodies is difficult. I may try out one of the free query-building tools

**Comment by qpwo** [comment]
This JSON appears to actually produce random results! I think it can be simplified some:
```
{
  "size": 10,
  "query": {
    "function_score": {
      "query": {
        "constant_score": {
          "filter": {
            "match": {
              "doc.text": "STRIKE"
            }
          },
          "boost": 1
        }
      },
      "random_score": {
        "seed": 5,
        "field": "_id"
      }
    }
  },
  "highlight": {
    "fields": {
      "doc.text": {}
    }
  }
}
```

**Comment by rgabbard** [comment]
@qpwo : Good progress! After you have this working, can you also experiment with using the document ID field as the field for `random_score`? [The ES documentation ](https://www.elastic.co/guide/en/elasticsearch/reference/6.4/query-dsl-function-score-query.html#function-random)warns using `_id` can be memory intensive.

**Comment by reckart** [comment]
FYI: INCEpTION is about to switch to using the ElasticSearch Java API to construct the query requests instead of manually fiddling the JSON together: https://github.com/inception-project/inception/pull/1181

**Comment by qpwo** [comment]
We can probably close this now, unless proper user-by-user seeding is important enough to get working first. (Right now the random seed is fixed, so different users who perform the same search will receive the same results I believe.)

**Comment by rgabbard** [comment]
A fixed seed is fine for our needs.  Thanks for fixing this, @qpwo !
